feat/open-source-guidelines
Widen/widen.github.io pull request #43
Opened 2020-10-28 20:44 UTC by feltnerm

Here's an initial page of Widen's public guidelines for open source projects. Feedback appreciated.

Requires https://github.com/Widen/jekyll-theme-guardian/pull/13 to get published, and then updated here.

2020-10-28 20:48 UTC, twilco commented on open-source.md
> +the core business functionality of Widen.
"will not" --> "does not"?

2020-10-28 20:48 UTC, dbeg requested changes

2020-10-28 20:48 UTC, dbeg commented on open-source.md
> +# Community Guidelines
The title is "Open Source Guidelines", slug is "/open-source", and h1 here is "Community Guidelines". Maybe just change the h1 to match?

```suggestion
# Open Source Guidelines
```

2020-10-28 20:49 UTC, twilco approved these changes
🎉

2020-10-28 20:51 UTC, feltnerm commented on open-source.md
> +# Community Guidelines
The `page.title` is Open Source Guidelines and that is rendered in the `<header>`. The Community and Project guidelines are part of the content.

2020-10-28 20:51 UTC, dbeg commented on open-source.md
> +Widen recommends the ISC. MIT and Apache are also viable. Talk with the Widen Developer Relations Committee if you have any questions.
Maybe link to our public email address?

```suggestion
Widen recommends the ISC. MIT and Apache are also viable. Talk with the [Widen Developer Relations Committee](mailto://engineering@widen.com) if you have any questions.
```

2020-10-28 20:51 UTC, dbeg commented on open-source.md
> +it might be worth erasing the entire commit history, or using an automated
Do we have any recommendations for a scrubbing tool? Might be helpful to link to one here and/or provide an example within http://github.com/Widen/new-public-project via a canned github action or something?

2020-10-28 20:52 UTC, feltnerm commented on open-source.md
> +the core business functionality of Widen.
What about 600e367 ?

2020-10-28 20:52 UTC, dbeg commented on open-source.md
> +# Community Guidelines
Yeah it just seems weird to me that the h1 of a page wouldn't match `page.title`. It's not a deal-breaker or anything, just seemed a little weird.

2020-10-28 20:59 UTC, feltnerm commented on open-source.md
> +# Community Guidelines
I think headers can be relative to their content. It's not like you only can have 1 h1 at the top level, you can have multiple levels. 🤷

2020-10-28 21:01 UTC, feltnerm commented on open-source.md
> +it might be worth erasing the entire commit history, or using an automated
I do not have any recommendations, but it was suggested to mention. The first google result has some information https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository. I frankly don't care how the history is change to removed secrets, as long as it is.

2020-10-28 21:02 UTC, dbeg commented on open-source.md
> +# Community Guidelines
I've always read and thought that there should only be one h1 element on a page (at least with respect to HTML5 and the notion of an `article` or w/e). But Google has said that there is no search penalty to multiple h1s on a single page.. so double 🤷 .

2020-10-28 21:15 UTC, dbeg approved these changes

2020-10-29 17:55 UTC, feltnerm commented on open-source.md
> +# Community Guidelines
I think also using `h1`s for the content makes the ToC work. For example:

```
# Foo

## Sub-foo

# Bar

## Sub-bar
```

Would become:

- Foo
  - Sub-foo
- Bar
  - Sub-bar

2020-10-29 18:02 UTC, mskelton commented on open-source.md
> +# Community Guidelines
I'd agree with Dan about the multiple h1s.  Seems like the post title should be an h1 and the rest should be h2s, h3s, etc.

2020-10-29 18:18 UTC, feltnerm commented on open-source.md
> +# Community Guidelines
Hmm... I see what you're saying, and my thought is that placing in a `<heading>` was giving it enough context to make sense.

Maybe we can whip up a filter that makes the markdown parser turn 

```
# Foo
``` 

into `h2`s instead of `h1` (`h++`s, per say) because essentially what we're saying is we want to disable the use of `h1`s in content?

FWIW, we have 7 `h1`s on `index.html` of the engineering blog (, and this current github page has 4).

2020-10-29 18:23 UTC, feltnerm commented on open-source.md
> +# Community Guidelines
This kramdown option:

```
header_offset
    Sets the output offset for headers

    If this option is c (may also be negative) then a header with level n will be output as a header with level c+n. If c+n is lower than 1, level 1 will be used. If c+n is greater than 6, level 6 will be used.

    Default: 0
    Used by: HTML converter, Kramdown converter, Latex converter
```

Looks promising.

2020-10-29 22:13 UTC, mskelton commented on open-source.md
> +# Community Guidelines
Interesting.  So, GitHub has one h1 in the header area (still part of the main tag though) as well as two h1s in the content but the two in the content are the same thing as one shows when scrolled down and the other will at the top.  The 4th is in a modal which is valid to do since it's separate from the main page content.

@avo Care to weigh in on accessibility here?

2020-10-30 14:25 UTC, avo commented on open-source.md
> +# Community Guidelines
Accessibility guidelines indicate that headings are generally used like page outlines. Newer standards specify one h1, then h2s are sub levels of h1, and h3 is a sub heading of an h2. The main landmark is generally where the h1 or main outline starts. You can have navigation rendered first starting with h2s because the nav supports the site and the page, as long as the navigation also is in an aside and/or nav. Models are interesting, especially when they are portals but articles I've seen suggest since they are supporting a flow on a page that they should also start at h2 since it's considered another "section" of the page, just displayed on top.

2020-10-30 14:28 UTC, avo commented on open-source.md
> +# Community Guidelines
I have also seen modals start at h1, which is also valid since they are almost like their own page doc. Modals with h1 on a page with h1 passes axe, but that also makes sense when you tab and are only tabbing through modal items and not the page underneath.

2020-11-03 16:16 UTC, feltnerm commented on open-source.md
> +# Community Guidelines
> **If you don't use semantic HTML tags, you should only use one `<h1>` per page**. Using more than one will not result in an error, but using only one is seen as a best practice. It makes logical sense — `<h1>` is the most important heading, and tells you what the purpose of the overall page is. You wouldn't have a book with more than one title, or a movie with more than one name! Having a single top-level title is also arguably better for screenreader users, and SEO.

> From HTML5, **if you use semantic HTML (e.g. semantic tags like the `<section>` tag), you can have multiple `<h1>` in the same page as long as they are correctly nested in a hierarchy**. As an example, you can have the main `<h1>` which is the page title, but then also another `<h1>` within a <section> tag somewhere in the page. The semantic of the HTML tags will then create this hierarchy, even if both headings have the same level. (See Section_Elements_in_HTML5 in Using HTML sections and outlines for more information.)

-- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

We're using semantic HTML, right? So multiple `<h1>`s are permitted as long as they are within an appropriate context.

2020-11-04 15:42 UTC, mskelton commented on open-source.md
> +# Community Guidelines
Interesting.  So, having an h1 in the `<article>` and `<header>` tag seems to be valid according to that MDN article, but having multiple h1s in the `<article>` which it seems this PR is introducing does not seem like it would be valid.

2020-11-04 16:38 UTC, avo commented on open-source.md
> +# Community Guidelines
Yes, it is valid to have more than one h1 if it makes sense to the outline of your page. Adding a header and h1 to a `section` for example will essentially promote it to a landmark. If you just have a `header` and `h1` on your page outside the context of section, aside, etc. then you should probably only have one, similar to having one `main`. If you use them within `article`, like you have an `h1` to name what your page is and then have a series of articles on your page that are separate things, then you can also have those use `header` and `h1`. Kind of like `header` and `footer`, your page has a high level `header` and `footer`, but then you can have then within `article` and `sections` for example. How you use it should signify the purpose... if its lending support to the page hierarchy or starting its own. As far as rendered code goes it should pass lighthouse, axe and other a11y tools.

2020-11-05 13:29 UTC, jweaver-widen approved these changes
🤙 🤙 🤙

2020-11-24 01:39 UTC, merged